version: "3.8"

services:
  app:
    image: postgres
    ports:
      - "3000:3000"
    restart: unless-stopped
    container_name: ticket-issuer
    depends_on:
      - redis

  redis:
    image: redis:7.4.8-alpine
    ports:
      - "6379:6379"
    container_name: ticket-issuer-redis
    volumes:
      - redis-data:/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: ticket-issuer-rabbitmq
    restart: unless-stopped
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  redis-data:
  rabbitmq-data:
